/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function applyPreparedOperationNative(prepared: NativePreparedOperation): Promise<unknown>

export interface NativePatchOperation {
  kind: string
  path: string
  moveTo?: string
  lines?: Array<string>
  chunks?: Array<NativeUpdateChunk>
}

export interface NativePreparedOperation {
  operation: NativePatchOperation
  absolutePath: string
  destinationPath?: string
  contents?: string
  diff?: string
}

export interface NativeUpdateChunk {
  context?: string
  oldLines: Array<string>
  newLines: Array<string>
  endOfFile: boolean
}

export declare function parsePatchNative(patch: string): Array<NativePatchOperation>

export declare function prepareOperationNative(operation: NativePatchOperation, cwd: string, includeDiff: boolean): Promise<unknown>
